name: Default template
description: The default template for all issues
body:
  - type: markdown
    attributes:
      value: |
        # Rules
        Test abc
  - type: checkboxes
    attributes:
      options:
        - label: I have read and agree to the rules
          required: true
