name: Default template
description: The default template for all issues
body:
  - type: markdown
    attributes:
      value: |
        Hi
  - type: checkboxes
    attributes:
      label: Label
      description: abc
      options:
        - label: Orange cat
          required: true
