name: Default template
description: The default template for all issues
body:
  - type: markdown
    attributes:
      value: |
        # Rules
  - type: markdown
    attributes:
      value: |
        Test abc
  - type: checkboxes
    attributes:
      label: "Please confirm:"
      options:
        - label: "I have read and agree to the rules"
          required: true
  - type: input
    attributes:
      label: "Describe the issue briefly in a few sentences:"
      description: "After creating the issue, you can add more details in a separate comment"
    validations:
      required: true
