name: Default template
description: The default template for all issues
body:
  - type: markdown
    attributes:
      value: |
        # Rules
  - type: markdown
    attributes:
      value: |
        **Please read this section carefully. Breaking the rules may result in you being blocked from interacting with this repository.**
  - type: markdown
    attributes:
      value: |
         Picocrypt is a "finished" piece of software and is in a maintenance-only stage. This does not mean the software is old, outdated, or abandonware, but that the focus is on fixing bugs and ensuring the software continues to work smoothly as opposed to actively developing new features. As well, my time as the developer is limited considering that Picocrypt brings me no monetary benefit and is entirely a gift of my time and skill to the community.
  - type: markdown
    attributes:
      value: |
        *To ensure that issues remain relevant and as time-efficient for me as possible, please follow the guidelines below depending on what the topic of your issue creation is.*
  - type: markdown
    attributes:
      value: |
        ### Bug reports or security issues
  - type: markdown
    attributes:
      value: |
        These are high-priority and the main purpose of leaving issues open for creation. Make the issue with a short description, and then once the issue is created, add a comment with as many details as possible. Ping me (@HACKERALERT) in the comment so that I can get to it as soon as possible. Keep in mind that I define "bug" as something wrong with Picocrypt's code itself. If it's not Picocrypt's fault, it's not a bug.
- type: markdown
    attributes:
      value: |
        ### Problems running/starting Picocrypt
  - type: markdown
    attributes:
      value: |
        Usually these issues are not directly because of Picocrypt's code. Create the issue and in a separate comment, provide details about the environment you're running in (like OS, OS version, DE, etc.). **Do not ping me initially.** Let the issue sit for at least *3 days* to allow other users to potentially help you resolve the issue. If after 3 days, you haven't figured things out, then you may ping me (@HACKERALERT).
- type: markdown
    attributes:
      value: |
        ### Support requests/usage questions
  - type: markdown
    attributes:
      value: |
        Create the issue and ask your question or support request in a separate comment. **Do not ping me initially.** Let the issue marinate for at least *5 days* to give other users a chance to help you first. If after 5 days, you have not received any assistance, then you may ping me (@HACKERALERT).
- type: markdown
    attributes:
      value: |
        ### Feature requests/suggestions
  - type: markdown
    attributes:
      value: |
        Picocrypt is mature software; I do not intend to add any new features. Generally, do not create any feature requests unless it's very minor and can be implemented with low effort and minimal impact on reliability. What is considered "minor" is subjective, but here is an example: "ability to decrypt a volume entirely in-memory" is pretty significant, while "press the Start button on Enter key" is relatively minor.
- type: markdown
    attributes:
      value: |
        ### Performance issues/improvements
  - type: markdown
    attributes:
      value: |
        Picocrypt prioritizes correctness and reliability over performance, so many parts of the code are written sequentially and don't use concurrency. This is intentional and need not be pointed out. Unless performance is absolutely atrocious to the point where it is indicative of a potential bug, do not make issues about performance.
- type: markdown
    attributes:
      value: |
        ### Other issues/generic topics
  - type: markdown
    attributes:
      value: |
        You will have to use your best judgement here. Read the sections above to get an idea of what I expect to see and do what you think is best. Ideally, ping me only if sufficient time has passed for other users to assist/answer you, or it is best addressed by me directly.
  - type: checkboxes
    attributes:
      label: "Please confirm:"
      options:
        - label: "I have read and agree to the rules"
          required: true
  - type: input
    attributes:
      label: "Describe the issue briefly in a few sentences:"
      description: "After creating the issue, you can add more details in a separate comment"
    validations:
      required: true
