name: build-windows

on:
  push:
    paths:
      - "src/*.go"
      - "src/go.mod"
      - "src/go.sum"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.22'
        check-latest: true
        cache-dependency-path: src/go.sum

    - name: Install dependencies
      run: |
        cd src
        go mod download

    - name: Build
      run: go build -ldflags="-s -w -H=windowsgui -extldflags=-static" -v -o Picocrypt.exe ./...
      env:
        CGO_ENABLED: 1

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: Picocrypt.exe
        if-no-files-found: error
        compression-level: 9
