name: build-snapcraft

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build-snapcraft:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install packages
      run: |
        sudo apt install -y gcc xorg-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa wget snapd
        sudo snap refresh
        sudo snap install snapcraft --classic

    - name: Copy Snapcraft files to source
      run: |
        mv dist/snapcraft/* src

    - name: Build Snapcraft
      run: |
        cd src
        lxd init --auto
        snapcraft

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-snapcraft
        path: |
          src/*.snap
        if-no-files-found: error
        compression-level: 9
