name: build-snapcraft

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build-snapcraft:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y gcc xorg-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa wget snapd
        sudo snap install snapcraft --classic
        sudo snap install multipass

    - name: Copy Snapcraft files to source
      run: |
        cp -r dist/snapcraft/* src/

    - name: Fix permissions
      run: |
        chmod -R a+rX src

    - name: List contents of src
      run: |
        ls -l src
        ls -l src/snapcraft.yaml || echo "snapcraft.yaml not found"

    - name: Build Snapcraft using multipass
      run: |
        cd src
        snapcraft
      env:
        SNAPCRAFT_BUILD_ENVIRONMENT: multipass

    - name: Upload .snap artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-snapcraft
        path: |
          src/*.snap
        if-no-files-found: error
        compression-level: 9
